swagger: "2.0"
info:
  title: "API de Carritos"
  description: "Documentación de la API para gestionar carritos."
  version: "1.0.0"
basePath: "/api"
schemes:
  - "http"
paths:
  /carts:
    get:
      summary: "Obtener todos los carritos"
      description: "Devuelve una lista de todos los carritos."
      responses:
        200:
          description: "Operación exitosa. Devuelve la lista de carritos."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Cart"
    post:
      summary: "Crear un nuevo carrito"
      description: "Crea un nuevo carrito en la base de datos."
      responses:
        201:
          description: "Operación exitosa. Carrito creado correctamente."
        400:
          description: "Error de validación. Datos incorrectos en la solicitud."

  /carts/{id}:
    get:
      summary: "Obtener un carrito por ID"
      description: "Devuelve un carrito específico según su ID."
      parameters:
        - name: "id"
          in: "path"
          description: "ID del carrito a buscar."
          required: true
          type: "string"
      responses:
        200:
          description: "Operación exitosa. Devuelve el carrito solicitado."
          schema:
            $ref: "#/definitions/Cart"
        404:
          description: "Carrito no encontrado. El ID proporcionado no coincide con ningún carrito."

    put:
      summary: "Actualizar un carrito por ID"
      description: "Actualiza un carrito existente en la base de datos según su ID."
      parameters:
        - name: "id"
          in: "path"
          description: "ID del carrito a actualizar."
          required: true
          type: "string"
        - name: "cart"
          in: "body"
          description: "Datos actualizados del carrito."
          required: true
          schema:
            $ref: "#/definitions/Cart"
      responses:
        200:
          description: "Operación exitosa. Carrito actualizado correctamente."
        404:
          description: "Carrito no encontrado. El ID proporcionado no coincide con ningún carrito."

    delete:
      summary: "Eliminar un carrito por ID"
      description: "Elimina un carrito existente en la base de datos según su ID."
      parameters:
        - name: "id"
          in: "path"
          description: "ID del carrito a eliminar."
          required: true
          type: "string"
      responses:
        204:
          description: "Operación exitosa. Carrito eliminado correctamente."
        404:
          description: "Carrito no encontrado. El ID proporcionado no coincide con ningún carrito."

definitions:
  Cart:
    type: "object"
    properties:
      products:
        type: "array"
        items:
          type: "object"
          properties:
            product:
              $ref: "#/definitions/Product"
            quantity:
              type: "integer"
